// Part of the following texture sets:
//	Eng_2	MW0052
//	Eng_2	MW0024	same texture, different offset (by 64px; 1/8th the texture)
//	Msg	ENGINE
//	MsgTest	MW0024	same texture, different offset (by 64px; 1/8th the texture)
//	MsgTest	MW0050
// NOTE the following textures are based off this one too:
// MW0022, MW0047, MW0051, MW0053 => (Eng_2) solus003 => (Ert_3) CopyofW_Core, W_CORE, W_CORE2, W_CORE3 => (MSG) MW0, MW0022, MW0047 => (msgtest) W_CORE => (res_2)
terrain_scale 128
render_material_only 1
render_pass
	{
	texture FAM\_ACC\MW0052
	shaded 1
	}