// Part of the following texture sets:
// Part of the following texture sets:
//	OPS_1	OPS1 (cont.)
//	OPS_1	PANEL (cont.)
//	OPS_1	PANEL1 (cont.)
//	OPS_1	PANEL2 (cont.)
//	OPS_1	PANEL3 (cont.)
//	OPS_1	PANEL4 (cont.)
//	OPS_2	OPS014 (pal swap)
//	OPS_2	OPS015 (pal swap)
//	OPS_2	OPS016 (pal swap)
//	OPS_2	OPS017 (pal swap)
//	OPS_2	OPS018 (pal swap)
//	OPS_2	OPS019 (pal swap)
terrain_scale 128
render_material_only 1
render_pass
	{
	texture FAM\_ACC\PANEL1
	shaded 1
	}
illum_map 1.0 FAM\_ACC\PANEL1_LUMA