// Part of the following texture sets:
//	Msg	W_BATH6	(16x16 -- pretend as 32x32) whitetiles3
//	Res_2	W_BATH6	(16x16 -- pretend as 32x32) whitetiles3
//	Related to:
//	Msg	W_WHITE	(original: 64x64 -- pretend as 128x128)	 whitetiles
//	Msg	W_BATH3	(32x32 -- pretend as 64x64) whitetiles2
//	MsgTest	MW0013	(32x32 -- pretend as 64x64) whitetiles2
terrain_scale 32
render_material_only 1
render_pass
	{
	texture FAM\_ACC\WhiteTiles
	shaded 1
	}