# flashing dendrite
# all overlays must be 1-bit transparency or force_alpha_key doesn't work for some reason
force_alpha_key 1
ani_frames 1
uv_clamp 1

render_pass {
	ani_rate 120
	blend ONE ONE
	texture { "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/dendb1" }
}

render_pass {
	ani_rate 90
	blend ONE ONE
	texture { "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/dendb2" }
}
