# flashing nerves
ani_frames 1

render_pass {
	ani_rate 90
	blend ONE ONE
	uv_mod SCROLL 2.5 0.1
	texture { "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/nerveb1" }
}

render_pass {
	ani_rate 120
	blend ONE ONE
	uv_mod SCROLL -2 -0.1
	texture { "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/trans" "material/shtup/obj/nerveb2" }
}
