render_material_only 1
ani_frames 1
terrain_scale 64

render_pass {
	ani_rate 50
	texture { "material/shtup/fam/p0036" "material/shtup/fam/p0036_1" "material/shtup/fam/p0036_2" "material/shtup/fam/p0036_3" "material/shtup/fam/p0036_4" "material/shtup/fam/p0036_5" "material/shtup/fam/p0036_6" "material/shtup/fam/p0036_7" "material/shtup/fam/p0036_8" "material/shtup/fam/p0036_9" "material/shtup/fam/p0036_10" "material/shtup/fam/p0036_9" "material/shtup/fam/p0036_8" "material/shtup/fam/p0036_7" "material/shtup/fam/p0036_6" "material/shtup/fam/p0036_5" "material/shtup/fam/p0036_4" "material/shtup/fam/p0036_3" "material/shtup/fam/p0036_2" "material/shtup/fam/p0036_1" }
}

render_pass {
	ani_rate 250
	texture { "material/shtup/fam/p0036a" "material/shtup/fam/p0036a_1" "material/shtup/fam/p0036a_2" "material/shtup/fam/p0036a_3" }
}

include ../../material/shtup/_screen.inc
